from time import sleep

print('Softario is now in Python')
sleep(2)
print('')
print('Loading...')
print('')
sleep(2)
print('𝑺𝒐𝒇𝒕𝒂𝒓𝒊𝒐')
print('Free Software for Free People')
print('Super Mario Forever')
print('BonziBUDDY')
print('CursorMania')
print('Google Chrome')
print('Murder Mystery')
print('')
print('Instructions')
print('1. Select The Name')
print('2. Copy It')
print('3. Paste It to Google')
print('4. Download Any Version You Want!')
print('5. Test It Now!')
